# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-28 18:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_status', models.CharField(max_length=100, unique=True)),
                ('redirected_link', models.CharField(max_length=100, unique=True)),
                ('created_by', models.CharField(max_length=100, unique=True)),
                ('user_giving_money', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades_money', to=settings.AUTH_USER_MODEL)),
                ('user_giving_skins', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades_skins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
