# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-28 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgomiddleman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='created_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_status',
            field=models.CharField(max_length=100),
        ),
    ]
