# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-05 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgomiddleman', '0005_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='trade_status',
        ),
        migrations.AddField(
            model_name='trade',
            name='amount_submitted',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='money_submitted',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='skins_assetids',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='skins_submitted',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
