# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-06 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgomiddleman', '0006_auto_20170705_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='money_reverted',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='time_posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='trade_reverted',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
