# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-08 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgomiddleman', '0007_auto_20170706_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='skins_submitted_icons',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='skins_submitted_name',
            field=models.TextField(null=True),
        ),
    ]
