# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgomiddleman', '0009_auto_20170709_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tradeUrl',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
